apiVersion: apps/v1
kind: Deployment
metadata:
  name: gin-simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gin-simple
  template:
    metadata:
      labels:
        app: gin-simple
    spec:
      containers:
      - name: gin-simple
        image: docker.io/song1206/gin-simple:v0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        # env:
        # - name: JAVA_OPTS
        #   value: "-Xmx512m -Xms256m -XX:MetaspaceSize=64m -XX:+UseParallelGC"
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 18081
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 18081
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: gin-simple
spec:
  selector:
    app: gin-simple
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP
